FROM bcit/centos:<%= image.vars['centos_version'] %>
<%= snippet('labels', binding) -%>

ENV RUNUSER none
ENV HOME /
ENV _BUILDAH_STARTED_IN_USERNS=""
ENV BUILDAH_ISOLATION=chroot

VOLUME /var/lib/containers

RUN yum -y --setopt tsflags=nodocs --setopt timeout=5 install \
    buildah \
<% if image.vars['centos_version'] == '8' -%>
    fuse-overlayfs \
<% end -%>
    podman \
 && rm -rf \
    /var/cache/* \
    /var/log/dnf* \
    /var/log/yum.* \
 && sed -i -e 's|^#mount_program|mount_program|g' -e '/additionalimage.*/a "/var/lib/shared",' /etc/containers/storage.conf \
 && mkdir -p /var/lib/shared/overlay-images /var/lib/shared/overlay-layers \
 && touch /var/lib/shared/overlay-images/images.lock \
 && touch /var/lib/shared/overlay-layers/layers.lock

<% if image.variant == 'centos6' -%>
RUN rm -rf \
    /etc/yum.repos.d \
    /etc/pki/rpm-gpg

COPY --from=bcit/centos:6-latest /etc/yum.repos.d /etc/yum.repos.d
COPY --from=bcit/centos:6-latest /etc/pki/rpm-gpg /etc/pki/rpm-gpg
<% end -%>
